### PR TITLE
[Feature Addition] Mish activation

### PR DESCRIPTION
**Pull request by thebhatman**
I have added the Mish Activation function. This resolves  https://github.com/facebookresearch/flashlight/issues/81. I am assuming the autograd would take care of the gradients. If I'm wrong, I'll add the gradient definition as well.

### CODE REVIEW

**Comment by avidov** [comment]
Thank you for the contribution.

> I am assuming the autograd would take care of the gradients.
Will you please add an autograd test in flashlight/tests/autograd/AutogradTest.cpp ?

Also please add a simple serialization test tests/nn/SerializationTest.cpp

**Comment by avidov** [comment]
Thank you for adding the serialization test.
My other request, in the comment above, was grayed out so I'll repeat it here.

Please add an autograd test in flashlight/tests/autograd/AutogradTest.cpp ?

**Comment by thebhatman** [comment]
I have added the test for Autograd. Can you please review it and check if it's the right way to implement? I am comparing the gradient obtained by autograd with the actual differentiation of mish.

**Comment by jacobkahn** [comment]
@thebhatman — we appreciate the contribution. After some discussion, we don't think this should be included in flashlight (at this moment).

We strive to include only methods, operators, and modules that have proven long-term success and results. This keeps our codebase lightweight, reduces the amount of maintenance we have to perform, and ensures a lack of opinionation.

If, down the line, the activation does show robustness across a variety of domains and tasks, we can certainly consider including it! Thanks again for the contribution.

**Pull request closed without merging**
